version: '3'
services:
 db:
  container_name: mysql-compose
  ports:
   - "3301:3306"
  image: mysql:5.6
  #Declaracion de variables de entorno dentro del yml
  #environment:
  # - "MYSQL_ROOT_PASSWORD=root"
  # Declaracion de variables de entorno desde un archivo externo
  env_file: common.env
