version: '3'
services:
 web:
  container_name: restart-compose
  image: restart-test
  build: .
  #Cunado es no no se debe definir el parametro caso contrario no construye.
  #Opciones que se pueden utilizar unless-stopped, always, on-failure
  # unless-stopped: Reinicia el contenedor siempre que no se haya detenido manualmente.
  # always: Reinicia el contenedor cada vez que se detenga.
  # on-failure: Reinicia el contenedor en caso de exister un error interno de ejecucion. 
  restart: unless-stopped
