version: '3'
services:
 web:
  container_name: nginx
  image: nginx
  ports:
  - "8081:80"
  networks:
   net:
    ipv4_address: 172.16.238.10
  volumes:
  - "vol:/usr/share/nginx/html"
networks:
 net:
  driver: bridge
  ipam:
   driver: default
   config:
   - subnet: 172.16.238.0/24
volumes:
 vol:
  
