version: '3'
services:
 wordpress_db:
  container_name: mysql-wordpress
  ports:
   - "3306:3306"
  image: mysql:5.6
  env_file: mysql-wordpress.env
  volumes:
   - $PWD/data:/var/lib/mysql
  networks:
   - wordpress-net
 wordpress:
  container_name: wordpress
  depends_on: 
   - wordpress_db
  ports:
   - "80:80"
  image: wordpress
  env_file: wordpress.env
  volumes:
   - $PWD/html:/var/www/html
  networks:
   - wordpress-net
networks:
 wordpress-net:
